import { Business } from "./types";

export const mockBusinesses: Business[] = [
	{
		id: "123",
		alias: "mock-business",
		name: "Mock Business",
		image_url: "https://source.unsplash.com/poI7DelFiVA",
		is_closed: false,
		url: "https://example.com/mock-business",
		review_count: 10,
		categories: [
			{ alias: "category-1", title: "Category 1" },
			{ alias: "category-2", title: "Category 2" },
		],
		rating: "4.5",
		coordinates: {
			latitude: "40.7128",
			longitude: "-74.0060",
		},
		transactions: ["pickup", "delivery"],
		price: "$$",
		location: {
			address1: "123 Main St",
			city: "New York",
			zip_code: "10001",
			country: "US",
			state: "NY",
			display_address: ["123 Main St", "New York, NY 10001"],
		},
		phone: "123-456-7890",
		display_phone: "(123) 456-7890",
		photos: [
			"https://example.com/photo1.jpg",
			"https://example.com/photo2.jpg",
		],
		is_claimed: true,
		reviews: [],
	},
	{
		id: "456",
		alias: "mock-business-2",
		name: "Mock Business 2",
		image_url: "https://source.unsplash.com/uB7q7aipU2o",
		is_closed: true,
		url: "https://example.com/mock-business-2",
		review_count: 20,
		categories: [
			{ alias: "category-3", title: "Category 3" },
			{ alias: "category-4", title: "Category 4" },
		],
		rating: "3.0",
		coordinates: {
			latitude: "37.7749",
			longitude: "-122.4194",
		},
		transactions: ["delivery"],
		price: "$$$",
		location: {
			address1: "456 Market St",
			city: "San Francisco",
			zip_code: "94102",
			country: "US",
			state: "CA",
			display_address: ["456 Market St", "San Francisco, CA 94102"],
		},
		phone: "555-555-5555",
		display_phone: "(555) 555-5555",
		photos: [
			"https://example.com/photo3.jpg",
			"https://example.com/photo4.jpg",
		],
		is_claimed: false,
		reviews: [],
	},
	{
		id: "789",
		alias: "mock-business-3",
		name: "Mock Business 3",
		image_url: "https://source.unsplash.com/nmpW_WwwVSc",
		is_closed: false,
		url: "https://example.com/mock-business-3",
		review_count: 5,
		categories: [
			{ alias: "category-5", title: "Category 5" },
			{ alias: "category-6", title: "Category 6" },
		],
		rating: "4.0",
		coordinates: {
			latitude: "34.0522",
			longitude: "-118.2437",
		},
		transactions: ["pickup", "delivery", "restaurant_reservation"],
		price: "$",
		location: {
			address1: "789 Vine St",
			address2: "Suite 123",
			city: "Los Angeles",
			zip_code: "90038",
			country: "US",
			state: "CA",
			display_address: ["789 Vine St", "Suite 123", "Los Angeles, CA 90038"],
		},
		phone: "111-111-1111",
		display_phone: "(111) 111-1111",
		photos: [
			"https://example.com/photo5.jpg",
			"https://example.com/photo6.jpg",
		],
		is_claimed: true,
		reviews: [],
	},
];
